### ISSUE TITLE
Choreonoid aborts in CI

### ISSUE THREAD

**Issue by mmurooka** [isri-aist/MultiContactController#1]
https://github.com/isri-aist/MultiContactController/actions/runs/4120205495/jobs/7114695001

```bash
+ choreonoid MCC_JVRC1_SampleField.cnoid --start-simulation
...
[info] Loading additional plugin configuration: /usr/lib/x86_64-linux-gnu/mc_plugins/etc/ROS.yaml
[info] Loading additional controller configuration: /home/runner/work/MultiContactController/MultiContactController/catkin_ws/devel/.private/multi_contact_controller/lib/mc_controller/etc/MultiContactController.yaml
[info] Loading additional controller configuration: /home/runner/.config/mc_rtc/controllers/MultiContactController.yaml
[info] Create controller MultiContactController
[success] [overwriteConfig] Overwrite with configuration jvrc1.
choreonoid: /package/mc_rtc/3rd-party/RapidJSON/rapidjson/document.h:1993: bool rapidjson::GenericValue<Encoding, Allocator>::StringEqual(const rapidjson::GenericValue<Encoding, SourceAllocator>&) const [with SourceAllocator = rapidjson::CrtAllocator; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::CrtAllocator]: Assertion `rhs.IsString()' failed.
/home/runner/work/_temp/fd9076cd-19f5-4bb4-a134-da7[484](https://github.com/isri-aist/MultiContactController/actions/runs/4120205495/jobs/7114695001#step:9:485)39b8c7.sh: line 29: 24184 Aborted                 (core dumped) choreonoid ${CNOID_FILE} --start-simulation
+ kill -2 24140
+ kill -2 24184
/home/runner/work/_temp/fd9076cd-19f5-4bb4-a134-da748439b8c7.sh: line 31: kill: (24184) - No such process
Error: Process completed with exit code 1.
```

**Comment by gergondet** [comment]
Hi @mmurooka 

I think this is related to the robots/env bug (it's just a different manifestation), I think it doesn't happen on the most recent runs?

**Comment by mmurooka** [comment]
Yes, it is solved by https://github.com/isri-aist/MultiContactController/commit/45838c6528b8b73105b0cd35e018b1676bb07bf4

**Comment by mmurooka** [comment]
The same problem still seems to occur at CI with low frequency.
https://github.com/isri-aist/MultiContactController/actions/runs/4134994629/jobs/7146853595
https://github.com/isri-aist/MultiContactController/actions/runs/4131754151/jobs/7139894439

**Comment by mmurooka** [comment]
I believe this problem has occurred several times on the local PC, and although I have not been able to reproduce it in gdb, the terminal output when the controller is started via choreonoid is as follows: The "[overwriteConfig]" message is printed just before the constructor of `fsm::Controller`, so the segmentation fault must be caused in the constructors of `MultiContactController`, `fsm::Controller`, or `MCController`. (BTW, the overwrite just before the controller constructor will be eliminated soon for sure.)

```bash
[info] Create controller MultiContactController
[success] [overwriteConfig] Overwrite with configuration jvrc1.
Segmentation fault
```

**Comment by gergondet** [comment]
Hi @mmurooka 

I think this should be definitely fixed by https://github.com/jrl-umi3218/mc_rtc/commit/1651fa9f088685f63459753befcdd49cb216f02f

**Comment by mmurooka** [comment]
@gergondet  Thank you!
