### ISSUE TITLE
Robot falls over when using DDP in CI simulation test

### ISSUE THREAD

**Issue by mmurooka** [isri-aist/MultiContactController#5]
See https://github.com/isri-aist/MultiContactController/actions/runs/6061308105/job/16449873366

The regular weekly CI runs did not fail in Aug 27, but started to fail from Sep 3. The major change in mc_rtc during this period is https://github.com/jrl-umi3218/mc_rtc/pull/385. It is not my intention to imply that this change is a mistake, but that the robot has started to fall over in CI simulation test due to some side effect caused by the change. (Indeed, this PR change could have an effect, since the falling point is where the robot reaches the hand while avoiding collisions)

https://github.com/isri-aist/MultiContactController/assets/6636600/4007b9ec-1889-43d0-8bc0-5ffa4284c2b8

**Comment by gergondet** [comment]
Thanks for raising this @mmurooka 

I have patched the PR to take into account the collision transform and that fixed the issue locally.

When mc_rtc head packages are updated we can re-run this or wait for the next scheduled CI.

**Comment by mmurooka** [comment]
Thank you @gergondet !
